name: Design Phnom Penh
favicon: null
layout_spectrum: 0.9644285610411316
typography_spectrum: 0.8920159144327044
title: 'Trying out ideas, making stuff, connecting people and our city.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.032493093982338905
  lightness: 0.8647104671690613
  saturation: 0.6779505871236324
  rhythmicContrast: 0.38486009812913835
purpose: []
